const SERVER_BASE_URL = 'http://localhost:8000/api/v1';
// const SERVER_BASE_URL = 'https://thebookstation.herokuapp.com/api/v1';
const FOODBOX_THEME_VARIANT = 'FOODBOX_THEME_VARIANT';
const FOODBOX_AUTH_TOKEN = 'FOODBOX_AUTH_TOKEN';
const FOODBOX_AUTH_DATA = 'FOODBOX_AUTH_DATA';
const FOODBOX_VIEW_MODE = 'FOODBOX_VIEW_MODE';

export const CONSTANTS = {SERVER_BASE_URL, FOODBOX_THEME_VARIANT, FOODBOX_AUTH_TOKEN, FOODBOX_AUTH_DATA, FOODBOX_VIEW_MODE};
